language: ruby
rvm:
  - 2.3.4
  - 2.2.7
  - 2.1.6
  - 2.0.0
  - jruby-9.0.0.0
  - 1.9.3
matrix:
  allow_failures:
    - rvm: 1.9.3
notifications:
  email:
    - api@mrcr.ru
script:
    - bundle exec rubocop
    - bundle exec rake
sudo: false
