# frozen_string_literal: true
source 'https://rubygems.org'

gemspec

group :development do
  gem 'rubocop', '~> 0.49.0'
end

group :test, :development do
  gem 'aruba', '~> 0.8.0'
  gem 'json', '>= 1.8'
  gem 'rake', '>= 0.8.7', '< 13.0'
  gem 'rspec', '~> 3.6.0'
  gem 'rspec-core', '~> 3.6.0'
  gem 'rspec-expectations', '~> 3.6.0'
  gem 'rspec-mocks', '~> 3.6.0'
  gem 'webmock', '~> 1.18.0'
end
